//// Generated by Selenium IDE
//
//import Utilities.ExtentTestManager;
//import com.relevantcodes.extentreports.LogStatus;
//import org.junit.Test;
//import org.junit.Before;
//import org.junit.After;
//import org.openqa.selenium.By;
//import org.openqa.selenium.Dimension;
//import org.openqa.selenium.WebDriver;
//import org.openqa.selenium.chrome.ChromeOptions;
//import org.openqa.selenium.chrome.ChromeDriver;
//import org.openqa.selenium.WebElement;
//import org.openqa.selenium.support.ui.ExpectedConditions;
//import org.openqa.selenium.support.ui.WebDriverWait;
//
//import java.time.Duration;
//import java.util.List;
//
//public class KCMRespondentsRespondentExclusionCRUDTest extends BaseTest {
//    private WebDriver driver;
//
//
//    @Before
//    public void setUp() {
//        ChromeOptions options = new ChromeOptions();
//        //options.addArguments("--headless=new");
//        driver = new ChromeDriver(options);
//
//    }
//
//    @After
//    public void tearDown() {
//        //driver.quit();
//    }
//
//    @Test
//    public void kCMRespondentsRespondentExclusionCRUD() {
//        ExtentTestManager.getTest().log(LogStatus.INFO, "kCMRespondentsRespondentExclusionCRUD Test.test is starting now", "");
//        try {
//            driver.get("https://d.kcmg.nl/login");
//            driver.manage().window().maximize();
//
//                WebDriverWait wait = new WebDriverWait(driver, 300);
//                wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("username")));
//
//
//            driver.findElement(By.xpath("//app-login/ion-header/ion-toolbar/ion-buttons/ion-button")).click();
//            Thread.sleep(8000);
//            driver.findElement(By.xpath("//ion-label[contains(.,\'Nederlands\')]")).click();
//            Thread.sleep(8000);
//            driver.findElement(By.xpath("//input[@id=\'username\']")).sendKeys("testautomation.donotdelete@procit.com");
//            driver.findElement(By.xpath("//input[@id=\'password\']")).sendKeys("KCM2020!#");
//            driver.findElement(By.xpath("//ion-button[contains(.,\'Log in\')]")).click();
//            Thread.sleep(15000);
//            //driver.findElement(By.xpath("/html/body/app-root/ion-app/ion-split-pane/ion-router-outlet/app-dashboard/app-header/ion-header/ion-toolbar/ion-buttons[1]/ion-button\n")).click();
//
//            Thread.sleep(16000);
//            driver.findElement(By.xpath("//ion-label[contains(.,\' Respondenten\')]")).click();
//            Thread.sleep(9000);
//            driver.findElement(By.xpath("//ion-button[6]")).click();
//            Thread.sleep(8000);
//            driver.findElement(By.xpath("//input[@name=\'EmailAddress\']")).click();
//            Thread.sleep(7000);
//            driver.findElement(By.xpath("//input[@name=\'EmailAddress\']")).sendKeys("procituser@procit.com");
//            driver.findElement(By.xpath("//div/ion-buttons/ion-button")).click();
//            Thread.sleep(7000);
//            driver.findElement(By.xpath("//ion-segment-button[@value=\'exclusion\']")).click();
//            Thread.sleep(7000);
//
//            //Add organisation level exclusion
//            driver.findElement(By.xpath("//ion-row[2]/ion-col[2]/ion-buttons/ion-button[2]")).click();
//            Thread.sleep(7000);
//
//            // Get all table rows
//            List<WebElement> rows = driver.findElements(By.xpath("//datatable-body-row"));
//            Thread.sleep(7000);
//            // Iterate through rows to find the one containing
//            for (WebElement row : rows) {
//                if (row.getText().contains("Bereik")) {
//                    WebElement clickOnScope = row.findElement(By.xpath(".//mat-select[@name='scope']"));
//                    Thread.sleep(3000);
//                    clickOnScope.click();
//                    Thread.sleep(3000);
//                    //Click on Organisation from dropdown
//                    WebElement addOrganisation = row.findElement(By.xpath("//span[@class='mdc-list-item__primary-text'][normalize-space()='Organisatie']"));
//                    addOrganisation.click();
//                    Thread.sleep(3000);
//                    WebElement addExclusionPeriod = row.findElement(By.xpath(".//input[@placeholder='Aantal dagen']"));
//                    Thread.sleep(3000);
//                    addExclusionPeriod.sendKeys("6");
//                    Thread.sleep(3000);
//                    WebElement clickCalender = row.findElement(By.xpath(".//input[@placeholder='Startdatum']"));
//                    Thread.sleep(3000);
//                    clickCalender.click();
//                    Thread.sleep(3000);
//                    WebElement addDate = row.findElement(By.xpath("//span[@class='owl-dt-calendar-cell-content owl-dt-calendar-cell-today']"));
//                    addDate.click();
//                    Thread.sleep(3000);
//                    WebElement applyCheckbox = row.findElement(By.xpath(".//ion-checkbox"));
//                    applyCheckbox.click();
//                    Thread.sleep(3000);
//                    //Click on save icon
//                    driver.findElement(By.xpath(".//ion-button[@helpcode='label-SaveDetailsInExclusion']")).click();
//                    break; // Exit loop once found and clicked
//                }
//                Thread.sleep(3000);
//            }
//            Thread.sleep(3000);
//
//            //add survey level exclusion
//            driver.findElement(By.xpath("//ion-row[2]/ion-col[2]/ion-buttons/ion-button[2]")).click();
//            Thread.sleep(5000);
//
//            wait.until(ExpectedConditions.presenceOfAllElementsLocatedBy(By.xpath("//datatable-body-row")));
//            List<WebElement> rows1 = driver.findElements(By.xpath("//datatable-body-row"));
//
//
//            for (WebElement row1 : rows1) {
//                if (row1.getText().contains("Bereik")) {
//                    WebElement clickOnScope = row1.findElement(By.xpath(".//mat-select[@name='scope']"));
//                    Thread.sleep(3000);
//                    clickOnScope.click();
//                    Thread.sleep(3000);
//                    //Click on Organisation from dropdown
//                    WebElement addOrganisation = row1.findElement(By.xpath("//span[@class='mdc-list-item__primary-text'][normalize-space()='Onderzoek']"));
//                    Thread.sleep(3000);
//                    addOrganisation.click();
//                    Thread.sleep(3000);
//                    WebElement addExclusionPeriod = row1.findElement(By.xpath(".//input[@placeholder='Aantal dagen']"));
//                    Thread.sleep(3000);
//                    addExclusionPeriod.sendKeys("6");
//                    Thread.sleep(3000);
//                    WebElement addSurvey = row1.findElement(By.xpath(".//mat-select[@name='Survey']"));
//                    Thread.sleep(3000);
//                    addSurvey.click();
//                    Thread.sleep(3000);
//                    WebElement selectSurvey = row1.findElement(By.xpath("//span[normalize-space()='Sample Survey']"));
//                    Thread.sleep(3000);
//                    selectSurvey.click();
//                    Thread.sleep(3000);
//                    WebElement clickCalender = row1.findElement(By.xpath(".//input[@placeholder='Startdatum']"));
//                    Thread.sleep(7000);
//                    clickCalender.click();
//                    Thread.sleep(7000);
//                    WebElement addDate = row1.findElement(By.xpath("//span[@class='owl-dt-calendar-cell-content owl-dt-calendar-cell-today']"));
//                    Thread.sleep(3000);
//                    addDate.click();
//                    Thread.sleep(3000);
//                    WebElement applyCheckbox = row1.findElement(By.xpath(".//ion-checkbox"));
//                    Thread.sleep(3000);
//                    applyCheckbox.click();
//                    Thread.sleep(3000);
//                    //Click on save icon
//                    driver.findElement(By.xpath(".//ion-button[@helpcode='label-SaveDetailsInExclusion']")).click();
//                }
//                Thread.sleep(7000);
//            }
//            Thread.sleep(7000);
//
//            //add survey group level exclusion
//            driver.findElement(By.xpath("//ion-row[2]/ion-col[2]/ion-buttons/ion-button[2]")).click();
//            Thread.sleep(8000);
//            wait.until(ExpectedConditions.presenceOfAllElementsLocatedBy(By.xpath("//datatable-body-row")));
//            List<WebElement> rows2 = driver.findElements(By.xpath("//datatable-body-row"));
//
//            for (WebElement row2 : rows2) {
//                if (row2.getText().contains("Bereik")) {
//                    WebElement clickOnScope = row2.findElement(By.xpath(".//mat-select[@name='scope']"));
//                    Thread.sleep(3000);
//                    clickOnScope.click();
//                    Thread.sleep(3000);
//                    //Click on Organisation from dropdown
//                    WebElement addOrganisation = row2.findElement(By.xpath("//span[@class='mdc-list-item__primary-text'][contains(text(),'Onderzoeksgroep') or contains(text(), 'Survey group')]"));
//                    Thread.sleep(3000);
//                    addOrganisation.click();
//                    Thread.sleep(3000);
//                    WebElement addExclusionPeriod = row2.findElement(By.xpath(".//input[@placeholder='Aantal dagen']"));
//                    Thread.sleep(3000);
//                    addExclusionPeriod.sendKeys("6");
//                    Thread.sleep(3000);
//                    WebElement addSurveyGroup = row2.findElement(By.xpath(".//mat-select[@name='SurveyGroup']"));
//                    Thread.sleep(3000);
//                    addSurveyGroup.click();
//                    Thread.sleep(3000);
//                    WebElement selectSurveyGroup = row2.findElement(By.xpath("//span[@class='mdc-list-item__primary-text'][normalize-space()='Bhumikagroup']"));
//                    Thread.sleep(3000);
//                    selectSurveyGroup.click();
//                    Thread.sleep(3000);
//                    WebElement clickCalender = row2.findElement(By.xpath(".//input[@placeholder='Startdatum']"));
//                    Thread.sleep(3000);
//                    clickCalender.click();
//                    Thread.sleep(3000);
//                    WebElement addDate = row2.findElement(By.xpath("//span[@class='owl-dt-calendar-cell-content owl-dt-calendar-cell-today']"));
//                    Thread.sleep(3000);
//                    addDate.click();
//                    Thread.sleep(3000);
//                    WebElement applyCheckbox = row2.findElement(By.xpath(".//ion-checkbox"));
//                    Thread.sleep(3000);
//                    applyCheckbox.click();
//                    Thread.sleep(3000);
//                    //Click on save icon
//                    driver.findElement(By.xpath(".//ion-button[@helpcode='label-SaveDetailsInExclusion']")).click();
//
//                    break; // Exit loop once found and clicked
//                }
//                Thread.sleep(7000);
//            }
//            Thread.sleep(7000);
//
//            wait.until(ExpectedConditions.presenceOfAllElementsLocatedBy(By.xpath("//datatable-body-row")));
//            List<WebElement> rows3 = driver.findElements(By.xpath("//datatable-body-row"));
//
//            // Iterate through rows to find the one containing "Bhumika"
//            for (WebElement row3 : rows3) {
//                if (row3.getText().contains("Bhumika")) {
//                    // Find the checkbox within this specific row
//                    WebElement checkbox = row3.findElement(By.xpath(".//input[@type='checkbox']"));
//
//                    // Wait for the checkbox to be clickable
//                    wait.until(ExpectedConditions.elementToBeClickable(checkbox));
//
//                    // Click the checkbox
//                    checkbox.click();
//                    driver.findElement(By.xpath("//ion-button[@helpcode=\"label-DeleteInRespondentExclusion\"]")).click();
//                    Thread.sleep(7000);
//                    driver.findElement(By.xpath("//span[contains(.,\'Ja\')]")).click();
//                    Thread.sleep(7000);
//                    break; // Exit loop once found and clicked
//                }
//            }
//            Thread.sleep(7000);
//
//            //delete exclusions
//            driver.findElement(By.xpath("//datatable-header-cell[@class='datatable-header-cell header-checkbox-cell ng-star-inserted']//input[@type='checkbox']")).click();
//            Thread.sleep(7000);
//            driver.findElement(By.xpath("//ion-button[@helpcode=\"label-DeleteInRespondentExclusion\"]")).click();
//            Thread.sleep(7000);
//            driver.findElement(By.xpath("//span[contains(.,\'Ja\')]")).click();
//            Thread.sleep(7000);
//
//            //delete respondent
//            driver.findElement(By.xpath("//ion-button[@helpcode=\"label-RespondentDetailsDelete\"]")).click();
//            Thread.sleep(7000);
//            driver.findElement(By.xpath("//span[contains(.,\'Ja\')]")).click();
//            Thread.sleep(7000);
//
//            ExtentTestManager.getTest().log(LogStatus.PASS, "kCMRespondentsRespondentExclusionCRUD Test.test is passed", "");
//        } catch (Exception e) {
//            ExtentTestManager.getTest().log(LogStatus.FAIL, "kCMRespondentsRespondentExclusionCRUD Test.test is failed ", "" + e.getMessage());
//        }
//
//
//    }
//}
